### ISSUE TITLE
OptimizelyApiClient.php - [] is not of type 'object'

### ISSUE THREAD

**Issue by jamesspittal** [webmarketingroi/optimizely-php#2]
Reported by @LCD344 in https://github.com/webmarketingroi/optimizely-php/issues/1

> Another thing that happened is that I can't update an experiment (just trying to unpause it) - code:
> 
> ````php
> $experiment->setStatus('running');
> $client->experiments()->update($experiment->getId(),$experiment,false,true);
> ````
> 
> ... and I get the next error:
> 
> `WebMarketingROI\OptimizelyPHP\Exception: [] is not of type 'object' in C:\wamp64\www\optimizely\vendor\webmarketingroi\optimizely-php\lib\WebMarketingROI\OptimizelyPHP\OptimizelyApiClient.php on line 339`

**Comment by LCD344** [comment]
This is technically solved I think - as now that the experiments are built in the right way, and they don't give that error any more

**Comment by jamesspittal** [comment]
Great - glad to hear it. Thanks @LCD344 - closing this now.
