### ISSUE TITLE
Outdated update query string parameters

### ISSUE THREAD

**Issue by LCD344** [webmarketingroi/optimizely-php#3]
I see that the query string parameters for the experiment are outdated - the code at the moment says : 

(Experiments.php line 185)

```php
        $queryParams = array(
            'override_changes' => $overrideChanges,
            'publish' => $publish
        );
```

The current query string parameter is only "`action`".

This prevent users from updating the activity of the experiment (running/paused/etc.)

**Comment by jamesspittal** [comment]
Thanks @LCD344 - I can see the function to which you are referring in `Experiments.php`, i.e.:

````php
    /**
     * Update an Experiment by ID
     * @param integer $experimentId
     * @param Experiment $experiment
     * @param boolean $overrideChanges If there are draft changes already in the experiment, you can override those changes by providing this query parameter.
     * @param boolean $publish Whether to publish the changes to the world.
     * @return Result
     * @throws Exception
     */
    public function update($experimentId, $experiment, $overrideChanges, $publish) 
    {
        if (!is_int($experimentId)) {
            throw new Exception("Expected argument of type Experiment");
        }
        
        if ($experimentId<0) {
            throw new Exception("Expected positive experiment ID argument");
        }
        
        if (!($experiment instanceOf Experiment)) {
            throw new Exception("Expected argument of type Experiment");
        }
        
        $queryParams = array(
            'override_changes' => $overrideChanges,
            'publish' => $publish
        );
        
        $postData = $experiment->toArray();
              
        $result = $this->client->sendApiRequest("/experiments/$experimentId", $queryParams, 'PATCH', 
                $postData);
        
        $experiment = new Experiment($result->getDecodedJsonData());
        $result->setPayload($experiment);
        
        return $result;
    }
````

@olegkrivtsov will investigate.

**Comment by olegkrivtsov** [comment]
Fixed.

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov 

@LCD344 Could you give this another try at your end with `0.9.0beta3` from packagist/composer (https://packagist.org/packages/webmarketingroi/optimizely-php)?

**Comment by LCD344** [comment]
It does indeed work! Now I have a program that goes into my experiments and unpauses them when my billing period starts again, yay.

Thanks for the good work and support :)

**Comment by jamesspittal** [comment]
Thanks for the feedback @LCD344 - sounds like a cool tool! (Are you planning to open source/release it?)

**Comment by LCD344** [comment]
Haha I didn't think about it. it's literally one page of code (And a bunch of composer dependencies) that I will run with cron - it checks if nothing is running (then it makes sense the pauses are because of billing) and if it is it resumes all the ones that were paused recently...

It's not much of a tool, and I feel like if I want to release it, it will actually become a real project and not a code I whipped up in an hour (and a bunch of you fixing the code lol) - but if you think it's a good idea Ill put some more effort into it - like not hard-coding the optimizely authorization token for example. :)

**Comment by jamesspittal** [comment]
Thanks @LCD344 - sent you an e-mail (`lcd344@yahoo.com`)
